### ISSUE TITLE
[suggestion] Seek FSF endorsement for Flathub repository

### ISSUE THREAD

**Issue by lofidevops** [flathub/flathub#116]
**User story:** I use an [endorsed distro](https://www.gnu.org/distros/free-distros.html) and I like the sound of Flatpak. I'd like to add a Flatpak repository that contains only free software, so that when I'm browsing GNOME Software I know every option is software I'd like to install.

**Suggested solution:** Speak to the FSF about endorsing Flathub. This may require a new endorsement mechanism (I'm not sure that [GNU FSDG](https://www.gnu.org/distros/free-system-distribution-guidelines.html) or [ethical repository criteria](https://www.gnu.org/software/repo-criteria.html) are exactly suitable.)

Note this may require stricter requirements than:

> All content hosted on Flathub must allow for redistribution and the license must be correct in the appdata file. [(Flathub: Review Guidelines)](https://github.com/flathub/flathub/wiki/Review-Guidelines)

for example:

>  This means these distros will include, and propose, exclusively free software. They will reject nonfree applications, nonfree programming platforms, nonfree drivers, nonfree firmware “blobs”, nonfree games, and any other nonfree software, as well as nonfree manuals or documentation. [(FSF: Free GNU/Linux distributions)](https://www.gnu.org/distros/free-distros.html)

**Notes:** Finally, if the plan is to support developers with distributable but non-free software, perhaps that software could go in an independent repository with a distinct name?

**Comment by TingPing** [comment]
Flathub currently gives users easy access to proprietary software. As the guideline says we ensure that these applications are correctly marked as such but I believe that still makes it something they would not endorse.

**Comment by cosimoc** [comment]
We did discuss using a separate repository vs. relying on metadata information provided by the repository for the use case of a free software-only GNOME Software, and decided to go with the latter for now.

Adding @alexlarsson and @hughsie here, since I'm not sure if such configuration is already possible in GNOME Software.

**Comment by TingPing** [comment]
@cosimoc In donf gnome-software has `show-nonfree-software`

**Comment by adityashah1212** [comment]
I think having two separate repos, like rpmfusion, would help a lot. Plus I believe this should allow distros with stricter rules about non-free software to package flathub with the distro release rather than having to install flathub separately. But I guess this is more of an enhancement than a requirement.

**Comment by alexlarsson** [comment]
Splitting the repo is complicated for some things. For instance auto-installing things like the nvidia drivers, these will currently only happen if the origin is the same as the runtime.

**Comment by kwill** [comment]
@alexlarsson Is that for the following case:

```
libre-utility
* Depends on: libre-library
* Optionally depends on: proprietary-nvidia-library
```

One solution might be to create two packages:

```
libre-utility (lives on flathub-libre)
* Depends on: libre-library (lives on flathub-libre)
```

```
libre-utility-with-nvidia (lives on flathub-proprietary)
* Depends on: libre-library (lives on flathub-proprietary)
* Depends on: proprietary-nvidia-library (lives on flathub-proprietary)
```

**Comment by F3nd0** [comment]
I think it's fairly important to split the repository (into libre and non-libre). Flathub is growing more popular in the libre software community; many programs (especially related to the GNOME project) use and _recommend_ it to distribute new releases. This may lead people to add a number of non-libre packages to their Flatpak package manager, in addition to the libre one they originally wanted, which should be prevented and avoided.

Marking packages as proprietary helps, for sure, (and thank you for presenting that information), but it should be taken a step further, so that such software does not have to be presented to the users who primarily just want to install libre packages from Flathub, and doesn't become directly installable without the explicit addition of a special repository.

**Comment by TingPing** [comment]
> This may lead people to add a number of non-libre packages to their Flatpak package manager, in addition to the libre one they originally wanted, which should be prevented and avoided.

That can be filtered at the client side, GNOME-Software has an option to hide non-free software for example.

**Comment by afranke** [comment]
> GNOME-Software has an option to hide non-free software for example.

Even when that’s set to hide non-free software I still see non-free software (e.g. Slack and Spotify). Is it really supposed to work?

**Comment by TingPing** [comment]
> Is it really supposed to work?

Looks like it wasn't... https://github.com/GNOME/gnome-software/commit/c3007f0e6b8229d9906647351d3deeae2d6c3682#diff-0c1853061785925df7a16fb3b81fde7d

**Comment by Calinou** [comment]
I think it's fair to assume that Flathub isn't going to be endorsed by the FSF. Therefore, this issue should be closed.
