### ISSUE TITLE
Photopea

### ISSUE THREAD

**Issue by RasheedAZ** [flathub/flathub#1436]
Hi. I've used Adobe for work my whole life and proprietary "Adobe level" products like Photopea and Qoppa PDF Editor are making transitioning to Linux possible for me.

The developer of Photopea (a free-to-use web based app) is happy to have it added to Linux repos and software centres but he does not know much about Linux and I myself do not know how to add it...

Is it possible to work with him (@photopea) and add this so all Linux users can benefit? Thanks.

https://github.com/photopea/photopea/issues/2026

**Comment by TingPing** [comment]
Sorry I'm not familiar with the project but is this just a website?

**Comment by TingPing** [comment]
It already has a web app manifest allowing browsers like Chrome to "install" it, which frankly is a good solution.

If somebody wanted to make it into a flatpak the easiest path is to simply make a thin wrapper with either WebKitGTK or QtWebEngine that simply opens the website.

**Comment by RasheedAZ** [comment]
Yes it's a web based app and I use it on Firefox on Zorin 15. 

Thanks I'll pass the suggestion on to him.

**Comment by photopea** [comment]
I am here guys :) Yes, Photopea is a website and it you can "install" (now, only in Chromium-based browsers). Now, Photopea is opened about 3300 times from a Linux computer every day. 

But I think @RasheedAZ wanted it to be integrated into Linux by default, so that even people who don't know it, could find it this way.

I think the wrapper sounds great, but I never made a wrapper, and I don't even have a Linux device to test it out :( Could you prepare such wrapper? Is there an online tool, where you put a URL of a website and it outputs the wrapper?

Or maybe you could make webapps a new category in Flathub, where users will only provide URLs and Flathub will do the rest. You could integrate Youtube, Instagram or Google Maps this way.

**Comment by RasheedAZ** [comment]
The webapp category idea seems best if they are able to do it. There are so many such apps and games that rival native programs. For wrapper, I found this after a quick search:

https://github.com/jiahaog/nativefier

https://github.com/eladnava/applicationize

**Comment by TingPing** [comment]
> Is there an online tool, where you put a URL of a website and it outputs the wrapper?

Sadly not :P

It would require a bit of work from somebody familiar with GTK or Qt.

**Comment by bilelmoussaoui** [comment]
It's up to the developers or the community to write and deploy such wrapper. Nothing to do from our side

**Comment by vikdevelop** [comment]
> I am here guys :) Yes, Photopea is a website and you can "install" it (now, only in Chromium-based browsers). Now, Photopea is opened about 3300 times from a Linux computer every day.
> 
> But I think @RasheedAZ wanted it to be integrated into Linux by default, so that even people who don't know it, could find it this way.
> 
> I think the wrapper sounds great, but I never made a wrapper, and I don't even have a Linux device to test it out :( Could you prepare such wrapper? Is there an online tool, where you put a URL of a website and it outputs the wrapper?
> 
> Or maybe you could make webapps a new category in Flathub, where somebody can only provide URLs and Flathub will do the rest. You could integrate Youtube, Instagram or Google Maps this way.
@photopea 
I created Webview wrapper of photopea & I uploaded on FlatHub :)
https://flathub.org/apps/details/com.github.vikdevelop.photopea_app
