### ISSUE TITLE
GTK3 apps do not allow folder selection on KDE Plasma desktop environment

### ISSUE THREAD

**Issue by glaubersm** [flathub/flathub#1442]
Arch Linux, KDE Plasma 5.18.4, flatpak 1.7.2.

It's impossible to select a folder with a GTK3 app installed from flathub.

Affected flatpaks on my system: Transmission torrent client, rhythmbox player and teleport.
The affected flatpaks trigger the KDE open file dialog, GTK3 apps from Arch repos trigger "Select a file" dialog that allows folder selection.

Compare the screenshots below showing the dialog that opens when I try to set download location in preferences of Transmission from Arch repos and from flathub.

Transmission from Arch repos:
![transmission arch](https://user-images.githubusercontent.com/15967631/78800674-19027900-7992-11ea-9647-41d5b70b49e0.png)

Transmission from flathub:
![transmission flatpak](https://user-images.githubusercontent.com/15967631/78800729-261f6800-7992-11ea-86d3-774cb7b3bd04.png)

**Comment by TingPing** [comment]
Well, I'm not sure why you report that to flathub.

However I believe this should all be fixed with the next releases of everything.

`xdg-desktop-portal` 1.7.1 allows selecting directories and GTK 3.24.15 supports it. Not sure about Qt but I'd expect it to have happened. If the latest development release of `-kde` doesn't support it then you should report it to them.
