### ISSUE TITLE
Problem with org.telegram.desktop/x86_64/stable

### ISSUE THREAD

**Issue by cryptomaniac512** [flathub/flathub#154]
When I try to run `org.telegram.desktop/x86_64/stable` I get this
```
This application failed to start because it could not find or load the Qt platform plugin "flatpak"
in "".

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Reinstalling the application may fix this problem.
```
Reinstalling application does not solve this provlem. How to fix it?

**Comment by Barthalion** [comment]
Please report issues under applications repositories. This should have been fixed by [this commit](https://github.com/flathub/org.telegram.desktop/commit/f8befee5b9ba9151be07c63dd5141bc19bc01095) that failed to build. Temporarily you can do `flatpak override --env=QT_QPA_PLATFORM='' --env=QT_QPA_FLATPAK_PLATFORM='' org.telegram.desktop` to workaround the problem.
