### ISSUE TITLE
Some json manifests do not parse?

### ISSUE THREAD

**Issue by mbooth101** [flathub/flathub#1814]
I recently wanted to parse all the manifests for all the apps on Flathub, using Python.

I am doing something like this:
```
           import json
           import requests

           manifest_data = json.loads(requests.get(url).content)
```

And to my surprise, some manifests would not parse. My script gives output like this:

```
Applications whose manifest failed to parse:
io.github.GnomeMpv: Invalid control character at: line 32 column 32 (char 937)
org.kicad_pcb.KiCad: Invalid \escape: line 191 column 40 (char 6931)
io.github.qtox.qTox: Expecting value: line 48 column 26 (char 1241)
net.oz9aec.Gpredict: Invalid control character at: line 54 column 48 (char 1580)
com.github.eudaldgr.elements: Expecting value: line 14 column 9 (char 530)
com.github.bleakgrey.tootle: Expecting value: line 10 column 9 (char 302)
org.kde.WaylandDecoration.QGnomePlatform-decoration: Invalid \escape: line 23 column 36 (char 801)
org.kde.kanagram: Expecting value: line 9 column 8 (char 206)
```

I guess `flatpak-builder` has a more lenient json parser. Is it worth filing bugs for these? Or can you recommend how I can parse them better in Python?

**Comment by refi64** [comment]
`flatpak-builder` uses json-glib's parser, which implements some JSON extensions. You can see [flatpak-external-data-checker](https://github.com/flathub/flatpak-external-data-checker/blob/119ad05f88ba699aadee87cb27bda79f8928ee20/src/lib/utils.py) (in particular `read_json_manifest`) for an example of using json-glib to parse the JSON, then re-serialize it and parse it via Python, in order to be able to handle the extensions.

**Comment by mbooth101** [comment]
@refi64 Aha, that's very helpful thanks. Feel free to close this bug in that case

**Comment by barthalion** [comment]
There's also `flatpak-builder --show-manifest` which we're using in buildbot.
