### ISSUE TITLE
package request; QOwnNotes

### ISSUE THREAD

**Issue by stavpup** [flathub/flathub#244]
https://github.com/pbek/QOwnNotes

QOwnNotes is the open source notepad with markdown support and todo list manager for GNU/Linux, Mac OS X and Windows, that works together with the default notes application of ownCloud.

**Comment by nedrichards** [comment]
Looks like a cool app, but we don't take packaging requests here. Every application is wanted and anyone is welcome to contribute a manifest, although we prefer to see the involvement of the upstream project. If you want to add and maintain it yourself then feel free to open a pull request - otherwise it's best to ask the upstream project themselves on their own bug tracker.
