### ISSUE TITLE
Please provide provenance information on flathub

### ISSUE THREAD

**Issue by rvandegrift** [flathub/flathub#264]
When browsing flathub, there's no easy way to find provenance information about an application - the links go directly to downloads for the flatpakref.  At the very least, each app should have a link to the repo that it's published from so a user can easily learn more about where it comes from.

Even better would be an info page with metadata like the maintainer of the flatpak, whether or not it's an official upstream packaging, version number, runtimes it uses, etc.

**Comment by MrMarukesu** [comment]
https://beta.flathub.org/apps

**Comment by TingPing** [comment]
Yes as linked the website is being entirely redone and will solve much of that. Some of that information isn't super important like runtime IMO, some of it is not known to the package (upstream maintainer or not), etc.

**Comment by rvandegrift** [comment]
I'm new to flatpak & flathub, so I'm thinking about questions like:
- how do I find contacts for submitting bug reports or patches?
- how could I determine that app X is trustworthy?

I'm not sure that my suggestions provide the best solution.  They're roughly inspired by the way Docker Hub handles these issues:
- automatically built images are marked with source repo info, so allow review of what's in the image
- some images are considered "official", either being distributed from the upstream devs or by Docker

**Comment by TingPing** [comment]
> how do I find contacts for submitting bug reports or patches?

Search for the app here: https://github.com/flathub

> how could I determine that app X is trustworthy?

Same as all distros ever made. You implicitly are trusting `flathub` packagers (and can verify there work on here), the rest of the trust is on upstream (especially for proprietary apps) and that for you to determine.

**Comment by nedrichards** [comment]
I think there is something interesting here, maybe reversed to highlight those that have community support rather than being offered by upstream (which could be a nice way into a 'claim my app' experience). This would need some metadata we don't currently easily have available for apps though so it's not a 'quick win'.

**Comment by omajid** [comment]
I can't +1 this enough. For all I know, any flatpak may have been published by random developer who built a random binary (possibly malware) and is now distributing it. As a user, I dont know if I can trust **anything** on flathub unless you explicitly provide some actual metadata like the publisher, how "official" the flatpak is and so on.

"official looking" applications are being used actively by malware authors right now: https://www.wired.com/2016/12/never-ever-ever-download-android-apps-outside-google-play/. Instead of making this problem worse, please look into addressing this issue.

**Comment by TingPing** [comment]
> For all I know, any flatpak may have been published by random developer who built a random binary (possibly malware) and is now distributing it. 

All build files on Flathub are readable and verifyable so while you may not know, anybody who cares to look can know.

Anyway I'm not against adding some way to show it is maintained by upstream.

> "official looking" applications are being used actively by malware authors right now: https://www.wired.com/2016/12/never-ever-ever-download-android-apps-outside-google-play/

This situation is not comparable for the reason I said above and the fact this is a curated repo not a random binary hosted on freeapps.ru.

**Comment by omajid** [comment]
> All build files on Flathub are readable and verifyable so while you may not know, anybody who cares to look can know.

If you expect flathub to be used by ordinary users (not developers), this approach will not work.

**Comment by Jehan** [comment]
I also noted the "publisher" tag on every app page on flathub displays as "Flathub maintainers". It doesn't look like this is a metadata which we can modify on our side (like with some Appdata), isn't it?

Anyway yeah it would be very nice if we could identify whether an app is distributed by upstream developers or third-party. Just today someone told us one didn't know the flatpak GIMP was official (even though linked from gimp.org) because this "publisher" tag is very confusing.

**Comment by TingPing** [comment]
> I also noted the "publisher" tag on every app page on flathub displays as "Flathub maintainers". It doesn't look like this is a metadata which we can modify on our side (like with some Appdata), isn't it?

If you click it it shows exactly who is committing to the package but no you can't modify it (nor should you be able to). On flathubs end we should be able to tag apps as official.

**Comment by TingPing** [comment]
Moving this issue here: https://github.com/flathub/linux-store-frontend/issues/146
