### ISSUE TITLE
error: Remote ‘flathub’ does not have a collection ID set, which is required for P2P distribution

### ISSUE THREAD

**Issue by tidux** [flathub/flathub#2643]
It appears the flatpak endpoint is misssing some features for allowing `flatpak create-usb` to work with applications installed from Flathub.

**Comment by barthalion** [comment]
Any idea @mwleeds? I think it's something we talked about it last yearish, but I don't remember the conclusion.

**Comment by mwleeds** [comment]
> Any idea @mwleeds? I think it's something we talked about it last yearish, but I don't remember the conclusion.

If you're asking why Flathub doesn't by default set a collection ID on users' remote configs, it's the topic of https://github.com/flathub/flathub/issues/676

As the last comment there says, @alexlarsson made a new metadata key that only enables the reworked sideloading support in recent versions of Flatpak, and the intention in doing that was so that we could set that metadata key for Flathub. I don't know of any reason we shouldn't do that. I have a collection ID set for flathub locally and it works for me.

**Comment by mwleeds** [comment]
For the record also the command to set a collection ID on flathub locally is `flatpak remote-modify --collection-id=org.flathub.Stable flathub`

**Comment by mwleeds** [comment]
(we can close this as a duplicate of #676)

**Comment by tidux** [comment]
Closing as duplicate.
