### ISSUE TITLE
Flatpaks do not use GTK theme

### ISSUE THREAD

**Issue by OlaoluwaM** [flathub/flathub#2673]
For the past couple of days I have been trying to get my flatpaks to use my GTK theme (Dracula), but to no avail. I gave general access to the `.themes` folder and set the `GTK_THEME` environment variable to Dracula but still no luck. However, I did notice that there is no Dracula theme on flathub, but I have been able to have my flatpaks adhere to the GTK theme once before despite this (using this tool [stylepak](https://github.com/refi64/stylepak)), don't know why it's not working now

OS: Fedora Workstation 35
Flatpak version:  1.12.2
DE: Gnome on Wayland

**Comment by barthalion** [comment]
GTK themes need to be packaged and published to Flathub, so there's no bug here. Stylepak just handles that locally for you.

**Comment by Francewhoa** [comment]
In addition to all the valuable comments and resolutions here. The fastest and easiest option that I know of to resolve this challenge using this [Flatseal](https://flathub.org/fr/apps/com.github.tchx84.Flatseal)

Steps to set a default theme for Flatpak applications: Navigate to **All Applications** horizontal tab ---> **Filesystem** group ---> **Other files** subgroup; Add the appropriate variable(s). Redo the same for **Environment** group. In the future, most future Flatpak applications you open will use the new theme.

![setting-theme-and-icon-for-all-flatpak-apps-through-flatseal](https://github.com/flathub/flathub/assets/119942/3d5391a0-9d76-41fd-ae97-5f483e4c232c)

<hr>

Detailed steps, additional information, and attributions at https://discourse.flathub.org/t/gtk4-apps-do-not-use-adwaita-dark/1327

**Comment by Francewhoa** [comment]
In addition to all the valuable comments and resolutions here. The fastest and easiest option that I know of to resolve this challenge using this [Flatseal](https://flathub.org/fr/apps/com.github.tchx84.Flatseal)

Steps to set a default theme for Flatpak applications: Navigate to **All Applications** horizontal tab ---> **Filesystem** group ---> **Other files** subgroup; Add the appropriate variable(s). Redo the same for **Environment** group. In the future, most future Flatpak applications you open will use the new theme.

![setting-theme-and-icon-for-all-flatpak-apps-through-flatseal](https://github.com/flathub/flathub/assets/119942/3d5391a0-9d76-41fd-ae97-5f483e4c232c)

<hr>

Detailed steps, additional information, and attributions at https://discourse.flathub.org/t/gtk4-apps-do-not-use-adwaita-dark/1327

**Comment by Francewhoa** [comment]
For those not familiar with the reason why Flatpak does not automatically use your default operating system (OS) theme is that, by default, all Flatpak applications are almost fully independent of your OS. Think of two independent devices inside your device. This is much stronger security. The downside is that sometimes, you need both your devices to communicate with each other. So that they can use shared settings or anything else to your liking.

In addition to all the valuable comments and resolutions here. The fastest and easiest option that I know of to resolve this challenge using this [Flatseal](https://flathub.org/fr/apps/com.github.tchx84.Flatseal)

Steps to set a default theme for Flatpak applications: Navigate to **All Applications** horizontal tab ---> **Filesystem** group ---> **Other files** subgroup; Add the appropriate variable(s). Redo the same for **Environment** group. In the future, most future Flatpak applications you open will use the new theme.

![setting-theme-and-icon-for-all-flatpak-apps-through-flatseal](https://github.com/flathub/flathub/assets/119942/3d5391a0-9d76-41fd-ae97-5f483e4c232c)

<hr>

Detailed steps, additional information, and attributions at https://discourse.flathub.org/t/gtk4-apps-do-not-use-adwaita-dark/1327
