### ISSUE TITLE
Slow downloads, change in servers? Australian server?

### ISSUE THREAD

**Issue by andrewpacific** [flathub/flathub#2946]
I live in New Zealand , any time I download from Australia I max out my bandwith in regards to download speed. (Currently 3.3MB/30Mb) This used to be the case when using flathub, now it's very slow. 

If I download an application that requires a new platform I have to go and find something to do to fill in the time like back in 90s.

Has there been a change in servers, is there a permanent Australian server? I don't expect one for New Zealand but one in Australia would server 10s of millions of people and be widely appreciated.

I'm currently downloading at 3.3MB/30Mb from a different server (as a comparison, not at the same time as flathub.)

**Comment by barthalion** [comment]
No change in servers. Does it happen with all applications/updates? We use Fastly CDN which provides multiple POPs in this region, so as long as it's a cache hit, it should be reasonably fast; obviously cache misses need to be fetched from our origins Netherlands/UK.

**Comment by razzeee** [comment]
Closing due to no reply.

**Comment by kekkoudesu** [comment]
@razzeee (sorry for the ping, I don't know if you get emailed anyway since this is a closed issue)

I'm facing the same issue as @andrewpacific and I'm from Australia. I've been downloading the Anki flatpak for about half an hour now at 140kB/s. It started off fairly fast but once it got to 40%, the download speed completely died. I can download 10MB/s easily. This isn't the first time I've faced this issue. Occasionally Flathub downloads are just really slow for me.

I need to restart Fedora to update, but it might be another ten minutes before I get the last 20MB of Anki downloaded, lol.

**Comment by kekkoudesu** [comment]
In the end, the download timed out. I started it again and eventually finished the download. The download at that point was hitting 20kB/s. Let me know how to provide logs if they would be useful! I'm not very familiar with Flatpak.

I was using KDE Discover but also just running `flatpak install flathub net.ankiweb.Anki`; the results were very similar.
