### ISSUE TITLE
-O2 -g or not -O2 -g?

### ISSUE THREAD

**Issue by jurf** [flathub/flathub#319]
(That is the question.)

This has been bugging me for a long time now. Several apps contain this:
```
  "build-options": {
    "cflags": "-O2 -g",
    "cxxflags": "-O2 -g"
  },
```
Others don’t. Some add it, some remove it.

So my question is – should we add/keep it, and if we should, why isn’t it default? And if it shouldn’t be default, _when_ should we add it?

**Comment by TingPing** [comment]
Nearly all projects set their own build flags, on ones that don't (usually plain makefiles) it makes sense to set it. Build systems like `meson` and `cmake` have explicit config-opts to set the build type which sets these.

**Comment by jurf** [comment]
But does it make sense to set it manifest-wide?

**Comment by jurf** [comment]
Hm, this is however surprisingly [often](https://github.com/search?l=JSON&q=org%3Aflathub+o2&type=Code) on Flathub.

**Comment by barthalion** [comment]
IMHO we should set some implied default (let it be `-O2 -g`). I guess the best place would be flatpak-builder itself though.

**Comment by jurf** [comment]
So what with the manifests that use it currently? Should we start removing it?

**Comment by jurf** [comment]
I noticed that a surprising amount of GNOME apps have this. I wonder how distros do this.

**Comment by TingPing** [comment]
Distros tend to try to set all CFLAGS themselves. To a degree that makes sense but also to a degree a point of Flatpak is to go with upstream.

**Comment by mtmiller** [comment]
I understand wanting to defer to upstreams on their own useful optimization level, and maybe other options. But is there at least a consensus on whether flathub apps should be built with `-g` or not? If upstream doesn't include it, should `-g` be added? If upstream defaults to cmake "Release" build type, should the manifest force it to "RelWithDebInfo"?

**Comment by TingPing** [comment]
In general yes including debug info is a good idea. On occasion you may want to disable that for massive dependencies or something I suppose.

**Comment by Erick555** [comment]
I think you shouldn't rely on upstream buildflags alone as there is no guarantee those were chosen with care and often are something minimal. This also leads to fragmentation as every app will be build in different and unknown way.

Moreover it means [security will be only opt-in feature](https://github.com/flathub/flathub/issues/353) instead of being standard. It took many years for distros to forcing secure build for all packages and now flatpak is starting from scratch which means moving back in time for a decade. There are also some "free meal" flags like `-pipe`, not using them is a waste of time and resources.

In my opinion flatpak apps should be build in consistent and secure way, not being a box of chocolates. I hope users won't have to wait for this for another years.

**Comment by barthalion** [comment]
There is [a pull request](https://github.com/flatpak/flatpak-builder/pull/142) adding possibility to define default build flags in the runtime, so we will most likely use it once it's merged.

**Comment by Erick555** [comment]
Thx, but why define it in the runtime instead of flatpak-builder? I think runtimes could set overrides when needed (probably won't be needed) but default flags should be defined in core as it would be easier to handle than setting it separately for multiple runtimes with different versions.

When you want to change default flags you would have to change it in every runtime versions available instead of just changing it in builder. This is better than setting it for every app but still not a best solution.

**Comment by alexlarsson** [comment]
compiler options depend on what a particular compiler supports in the SDK used, so the default compiler options should be decided by the sdk/runtime. For example, if a new security feature is added, we can't default to that in flatpak-builder, because that would cause older runtimes to stop building. Even worse is if an old security feature is deprecated/removed in favour of a new one and we happened to default to that in flatpak-builder.

**Comment by alexlarsson** [comment]
Anyway, the reason CFLAGS is set most everywhere is because while modern systems like cmake and meson auto-pick these options from the build-type, autoconf-base systems do not, so the CFLAGs set here is similar to the default values set by most distros. And the reason -g is in there is to make the builds get debug-info so that the separate debuginfo extensions work.

We want to add the default flags to the sdk, but I don't think we can enable that until fd.o 1.8, or otherwise we risk breaking existing app builds.

**Comment by Erick555** [comment]
QMAKE also tends to ignoring buildflags.

This is something which needs testing for sure but I would prefer making decisions based on testing, not guessing. We are talking about widely used flags tested across many distros for a long time. I heard that 1.8 isn't coming anytime soon and waiting for it may be wasted time if something can be done now.

**Comment by jurf** [comment]
Soooooooo…

Any update on this? 18.08 is out.

**Comment by Erick555** [comment]
Do you mean [those](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/18.08/project.conf#L95)?

**Comment by barthalion** [comment]
They don't seem to get exported into environment with `flatpak run --command=sh org.freedesktop.Sdk//18.08`.

**Comment by TingPing** [comment]
`flatpak run --command=cat org.freedesktop.Sdk/x86_64/18.08 /etc/flatpak-builder/defaults.json`

**Comment by Erick555** [comment]
I guess this can be closed then?

**Comment by jurf** [comment]
Can I just copy paste them into my not-yet-18.08 apps?

**Comment by TingPing** [comment]
Yup.
