### ISSUE TITLE
Proposal: Document clear plan for EOL of runtimes

### ISSUE THREAD

**Issue by ahayzen** [flathub/flathub#364]
# Rational

The flatpak website [0] claims that flatpak's "Future-proof builds. Runtimes are forward compatible, irrespective of distribution changes. Flatpak applications run on new Linux distribution versions as they are released." This sounds great ! If I write my application A against runtime B version 1, it will work forever !

Now some, for example, proprietary applications may decide to use runtimes in flathub (and maybe they are not in flathub itself). If a runtime EOL's and is removed from flathub, suddenly these apps that depend on the runtime version will break with no way to rebuild them against a newer runtime.

I think there should be a clear plan for what happens to EOL'd runtimes, yes they are EOL, unsupported, a security risk etc but the user should still have a way to use them if required.

Ubuntu [1], Debian [2], Fedora [3] etc all have such a system for moving their EOL'd repositories to an archive.

# Proposal

My proposal is to have a repository on flathub, called something like unsupported, archive, oldreleases. Which contains a copy of any EOL'd runtimes.

This then means that the user can add the repository manually to satisfy the app which requires the runtime, and therefore meeting the claim of "future-proof builds".

Eg
```
$ flatpak remote-add --if-not-exists flathub-unsupported https://flathub.org/repo/flathub-unsupported.flatpakrepo
```

# Documentation

If such a proposal is chosen, it should be clearly documented on flathub.org/docs/wiki so that users and developers can find and understand this information.

# Refs

0 - https://flatpak.org/
1 - http://old-releases.ubuntu.com/releases/
2 - http://archive.debian.org/debian/dists/
3 - http://archive.fedoraproject.org/pub/

**Comment by TingPing** [comment]
I agree we need clear information on support length. CC @alexlarsson

**Comment by nedrichards** [comment]
For FDo 1.6 the maximum security lifetime is the same as the underlying Yocto Linux (minus any less comittment from alex or other comitters to rebase it). I'm not aware on the policy for FDo 1.8 (BuildStream based) but that's not released yet.

I do not believe that any GNOME runtime currently has 'official' release team support, last I heard that was planned to occur with a migration to BuildStream based systems, so, possibly 3.30). However there's obviously a wide community effort to update it.

For KDE, the underlying Qt lifetimes are that 5.9 is LTS has support until 2020, wheras I believe 5.10 is supported until November 2018. The KDE team seems to update to new versions of the KDE frameworks in a 'rolling' fashion within these lifetimes, we'd need to check with them to know what their support lifetime is.

As a side note to this - moving things between repos without extra tooling is a non-starter for users. That tooling is being created in flatpak (and we'll need management scripts etc. as well) but it doesn't yet fully exist. (I know this because Endless needs a bunch of it!)

**Comment by damianatorrpm** [comment]
+1 for a mirror which keeps old runtimes - forever

**Comment by barthalion** [comment]
It's safe to say after 2 years that we do not delete old runtimes from Flathub.
