### ISSUE TITLE
Installed Flatpak Cache Files 

### ISSUE THREAD

**Issue by elswerky** [flathub/flathub#414]
Is There an option to save Cache files of installed Flatpak apps ?? 
i mean the file which i can use to install them later offline 

like exe files of windows 

and deb files present in /var/cache/apt/archives        (cached deb files of installed apps on debian based distro which can be used for offline installation of these apps )

and tar.xz files of arch based distro can be found in /var/cache/pacman/pkg 

but for flatpak apps i don't know where is the cache files 

and it won't be good if there is no cache files or flatpak apps can't be installed offline!

i hope you reply me and help me concerning that!

**Comment by nedrichards** [comment]
This isn't an issue for flathub, more for the flatpak project directly. https://github.com/flatpak/flatpak so I'm going to close this issue here. However I'll give you a quick answer.

The short answer is - it doesn't quite work like that in flatpak, but you can export apps from your repository to a flatpak bundle using the `flatpak build-bundle` command. However that doesn't work terribly well and has a number of drawbacks as those apps are more difficult to update and manage going forwards.

My employer, Endless, has been working on this in flatpak and ostree to support USB sticks, local networks and lots of other offline and poor connectivity use cases. This is currently in experimental API but we expect to have it working and deployed properly in the not too distant future and there's lots of work going on to support this.

**Comment by elswerky** [comment]
thank you for explanation
