### ISSUE TITLE
Provide hosting for sources

### ISSUE THREAD

**Issue by eszlari** [flathub/flathub#435]
I was about to update Krita to 4.0.4 and now download.kde.org is down. I think it is time for flathub to host their own sources.

**Comment by oiaohm** [comment]
If you go though gpl compliance guide.
https://www.softwarefreedom.org/resources/2008/compliance-guide.html

 "However, you must ensure that users can easily find the source code at the time they download the binary." <<  This is in 4.1.4. 

On github Krita could be a checked out fork under the flathub account so if the KDE account moves for some reason required Krita source does not magically disappear from where users are told to find it.

So while hosting the flatpak binaries of gpl/lgpl... copyleft programs it would be a good idea to host/fork source as well.   Yes this covers Krita and may other programs. 

In someways it would be good to have a flatpak source bundle package with everything fairly much set to allow remaking a flatpak for architectures that flathub does not support.

**Comment by ramcq** [comment]
You can flatpak install flathub foo.bar.Sources and get the tar/git/etc sources which went in to a certain build.

**Comment by ramcq** [comment]
(Also, as a side point, Flathub also caches the sources we download so that we have the capacity to rebuild even when SourceForge is being terrible. Like always.)

**Comment by eszlari** [comment]
> You can flatpak install flathub foo.bar.Sources and get the tar/git/etc sources which went in to a certain build.

This is not what this bug report is about.

> (Also, as a side point, Flathub also caches the sources we download so that we have the capacity to rebuild even when SourceForge is being terrible. Like always.)

I know, but from my experience, this does not always work reliably. Also in this case (krita), the tarball was never uploaded before.

**Comment by eszlari** [comment]
Btw: I solved it by uploading the tarballs to github: https://github.com/eszlari/flatpak-sources/releases

But I think, everybody maintaining their own mirrors is not an elegant solution.

**Comment by ramcq** [comment]
Ah sorry @eszlari, I got distracted from the real issue by @oiaohm. You're saying that Flathub should provide somewhere to upload source to so that the first time we build, if the original origin is unavailable, it's stored inside our infrastructure? I don't think that's a common enough need that it can't be covered by either, adding the file into your git project and just using a "file" origin, or relying on the source caching where the repo server fetches the source into the cache before the build starts.

But in a sense, Flathub gets some (admittedly small) comfort/benefit in the app source coming from the app publisher, and that being easy to inspect. If the Krita we're building doesn't come from kde.org, it's much harder to reason that it's a legitimate copy of the upstream version. The other layers being caching etc doesn't contradict that, but providing a new origin does.
