### ISSUE TITLE
Possible abuse of the app update system.

### ISSUE THREAD

**Issue by BeverlyCode** [flathub/flathub#4697]
There are two main incentives to abuse the system for updating apps:
* Bump the app on the front page updated list
* To track active users, if your force an update every week you get a weekly updated metric which will give you a weekly insight of active users.

These are solvable, not huge problems, but probably could do with fixing. Adding an active user metric to the stats would prevent people abusing it to obtain this metric, otherwise people who realise they can abuse it will probably do so as this metric can be quite valuable.

As for bumping on the front page, who really cares I guess, not the end of the world but maybe a bump limit per week or something can be added if not already in place so people can only bump their app on the front page once a week with an update, even if they update multiple times in a week.

**Comment by JakobDev** [comment]
Do we know how many People are actually doing this?

**Comment by Erick555** [comment]
I think it's quite inadequate example as mentioned app doesn't look official, is [broken](https://github.com/flathub/com.jagex.RuneScape/issues/211) and the company is _killing the Linux support_ according to the [comment](https://github.com/flathub/com.jagex.RuneScape/issues/217#issuecomment-1758020803). The updates are done by flathub bot.

I seriosuly doubt this is relevant example of abusing flathub.

**Comment by razzeee** [comment]
> My main concern is not so much people exploiting it but the strain that fictitious updates would potentially put on the Flathub bot build system. If people want to bump their app that's pretty unfair to other people who are legitimately updating their apps but it's the equivalent to spilt milk to me in comparison to creating fictitious load on the build system which is quite serious and can affect many more publishers in a much worse way.

This will hopefully change a bit with build tokens, when some apps will start to build on their own build servers

**Comment by mijorus** [comment]
Hi, is this related somehow to the fact that some builds are getting cancelled for no apparent reason right not?

**Comment by razzeee** [comment]
No - but the buildbot was restarted today, to try to fix the builds not setting github status promptly

**Comment by bbhtt** [comment]
> My main concern is not so much people exploiting it but the strain that fictitious updates would potentially put on the Flathub bot build system. 

All build requests go through the queue system in order of they are requested. If you have specific cases of these fictitious updates/updates with malicious intent please report it via the email listed in the GitHub homepage.

Apps can have legitimate dependency updates many times a day with how the current x-checker workflow works, for example if they have x-checkers set up for a bunch of python packages. There is no generic way to recognise such fictitious updates over legitimate ones without going through each on a case-by-case basis.

And I don't know why anyone would go through the trouble of doing all that just to get some usage metrics which they can easily do by implementing it in the app or staying up in the recently updated list which seems to be an even weaker reason and then get easily caught because the builds are monitored.

I'm closing this as this seems to be a non-existent problem right now.
