### ISSUE TITLE
Unreachable verified information

### ISSUE THREAD

**Issue by aleixpol** [flathub/flathub#4917]
I've been looking into implementing the verified info as discussed with bart in FOSDEM.

I've looked into implementing in Discover but I've noticed that this information is filtered out by libappstream because it's deemed as non-compliant to the spec:

```
$ appstreamcli validate appstream.xml.gz  --no-net |& grep com.cassidyjames.butler
I: com.cassidyjames.butler:14859: developer-name-tag-deprecated
```

This information should be provided using the custom tag:
https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-custom

**Comment by ximion** [comment]
The problem here is actually that `metadata` was actually a proprietary GNOME-specific tag that nobody but GNOME ever supported and that was switched away from even by appstream-glib long in the past.

Unfortunately GNOME Software parses all XML again (with libappstream and libxmlb), and apparently when this was implemented somehow the old GNOME-only tag was used as well as it being implemented through libxmlb, bypassing all validation.

The only way Flathub could generate this tag is by either writing the XML manually (boo! :-P) or by forcing libappstream-glib to emit data for an AppStream version < 0.6 - both not ideal.

The tag that warns about this in AppStream is actually https://www.freedesktop.org/software/appstream/docs/chap-Validation.html#asv-nonstandard-gnome-extension which is only an *info* because I didn't want to make some GNOME data invalid while migrating to a supported tag. Maybe that was a mistake and I'll change that at least for this tag.

I'll also fix this in GNOME Software to it reads the `custom` tag, which works like `metadata` but has actually been supported everywhere for a long time.

So all in all, a bit unfortunate bad luck, but we can solve this (even if it means Flathub needs to emit both tags for a while...).
