### ISSUE TITLE
Microsoft Edge package download speed is slow

### ISSUE THREAD

**Issue by arch3rtemp** [flathub/flathub#4933]
Hello,

I live in the Republic of Georgia. I've noticed that every time I update my Flatpak-installed Microsoft Edge, the download speed is extremely slow (around 600Kb/s), compared to the download speed of other packages.

Best regards

**Comment by AppleMayExist** [comment]
The [manifest](https://github.com/flathub/com.microsoft.Edge/blob/beta/com.microsoft.Edge.yaml#L107) for the flatpak defines Edge as "extra data," which means flatpak would be downloading Edge directly from Microsoft's servers, not Flathub. This is because Edge is proprietary, and not legally re-distributable. Unfortunately, I believe there is not much Flathub can do about this, only Microsoft.

Please note I am not affiliated with Flathub, and am not an authority on this topic, so please correct me if I'm wrong.

**Comment by bbhtt** [comment]
Yes, Flathub hosts only the appdata, launcher, icon desktop file etc. and the two libaries which in total should be a few MBs.

The edge deb which is the actual application is downloaded directly on the users machine. So any slowness should be between the PC and microsoft's servers and no Flathub.

If you think this is not the case, please reopen. Thanks.
