### ISSUE TITLE
org.winehq.Wine maintainer MIA

### ISSUE THREAD

**Issue by james2432** [flathub/flathub#4939]
https://github.com/flathub/org.winehq.Wine

Maintainer has gone MIA and doesn't have any activity on github since November 2023

See:

https://github.com/flathub/org.winehq.Wine/issues/107

**Comment by james2432** [comment]
![Screenshot from 2024-02-13 20-26-13](https://github.com/flathub/flathub/assets/498547/a3ca3a57-4294-4f19-82c4-40d038cdcf49)
I think the country of Origin, may explain why they've not been very active in past few months

**Comment by bbhtt** [comment]
So to provide an update here, gasinvein came back on #flatpak and said they'll resume activity in April, but it's unclear if they'll continue to maintain Wine because they also said, they don't have access to a Linux PC anymore.

So in the meantime, if you need anything in Wine to be merged or looked at ping one of the admins (me, Hub or barthalion) or ask in #flathub:matrix.org. If they can't resume activity, we'll roll new branches of the wine baseapp when the need arises.
