### ISSUE TITLE
Import freedesktop 18.08 into FlatHub

### ISSUE THREAD

**Issue by Wetrain** [flathub/flathub#495]
During GUADEC, we discussed with Rob & Alex about how we should approach getting the latest version of the freedesktop-sdk (18.08) into FlatHub., so we can begin to test applications on the latest runtime.

It was decided that, the best solution would be for FlatHub to pull in the latest release from our releases server located here: https://cache.sdk.freedesktop.org/releases/

This issue is to start a discussion on how we should start the processes of completing this task, and if there are any further tasks that need to be completed before this import can occur.

**Comment by alexlarsson** [comment]
This is pretty simple to start with. We already import the 1.6 BaseSdk like this, because we don't do yocto on flathub.

Here is where the config for this lives: 
  https://github.com/flathub/buildbot-config/blob/master/builds.json#L120

Basically, we just need the url, the gpg key and a set of (partial) refs to import from it. Given this admins can import manually by triggering an import job at https://flathub.org/builds/#/builders/7

However, we really want some more things:
 * Automatically trigger an import from the sdk.freedesktop.org side when there is a new stable build.
 * Fix the dependency handling in buildbot so that importing a ref triggers dependent things to rebuild (we only do this for things built by buildbot right now).

**Comment by Wetrain** [comment]
That's great news!

We are currently pushing the releases here:

* https://cache.sdk.freedesktop.org/releases/

We also have the .flatpakrepo file hosted there, which contains the GPG key:

* https://cache.sdk.freedesktop.org/freedesktop-sdk.flatpakrepo

**Comment by alexlarsson** [comment]
This is imported now. For the moment it needs manual import each time though, we should look into automating that.
