### ISSUE TITLE
Flatpak image contains screenshots

### ISSUE THREAD

**Issue by soyersoyer** [flathub/flathub#5114]
They are pretty big (2.2M)
Why is it good?
When I want to download an app I have internet, the screenshots are taken from the Internet.
When I have the app, I don't care about screenshots.

**Comment by bbhtt** [comment]
Can you explain what you mean? 

Screenshots from the metainfo file are mirrored by flatpak-builder when building the Flatpak and saved into `share/app-info/media` directory by appstreamcli. This is done to have a local cache of the images and to preserve privacy so that you don't need to connect to random webservers to download images.

**Comment by soyersoyer** [comment]
> This is done to have a local cache of the images and to preserve privacy so that you don't need to connect to random webservers to download images.

Does it download all of the screenshots from all of the applications? Or when and how does it preserve the privacy?

A few months ago my application (hu.irl.cameractrls) on flathub was 600kb, and I think that's a good size for such an application. Now it's 2.7 Mb. The app doesn't use the screenshots. And I can see the screenshots in the software app even if the app is not installed.

**Comment by bbhtt** [comment]
> Does it download all of the screenshots from all of the applications?

When the build is done on Flathub servers, appstreamcli downloads the images, converts it to thumbnail and original variants and saves it. This is shipped in every Flatpak.

> Or when and how does it preserve the privacy?

a) Screenshots are mirrored to Flathub's CDN, so whenever you open an app in GNOME Software/Discover, it doesn't connect to a random website which may or may not be evil

b) It is also saved to the local cache for exactly the same reason.

> And I can see the screenshots in the software app even if the app is not installed.

Those are fetched from Flathub directly when not installed.

> The app doesn't use the screenshots. 

What do you mean? I see a bunch of screenshots here https://flathub.org/apps/hu.irl.cameractrls

> A few months ago my application (hu.irl.cameractrls) on flathub was 600 kB, and I think that's a good size for such an application. Now it's 2.7 MB

So are you saying the size increased due to screenshots? Download and install size can increases for a number of reasons, maybe they started shipping extra libraries etc.

**Comment by bbhtt** [comment]
Each image is converted into 3 thumnails

**Comment by bbhtt** [comment]
This is not an issue, it is just how things work with appstream.

**Comment by soyersoyer** [comment]
But did appstream work differently last year?

**Comment by bbhtt** [comment]
> But did appstream work differently last year?

Yes we switched from deprecated appstream-glib to libappstream https://docs.flathub.org/blog/improved-build-validation

**Comment by soyersoyer** [comment]
I reduced the number of screenshots to 1, so its under 1MB again! :)

**Comment by razzeee** [comment]
If you think this should work differently, raise it here https://github.com/ximion/appstream/issues

**Comment by soyersoyer** [comment]
I am a bit tired, maybe next week.
It's a lot of excess data. 5 000 000 download / day * 1 MB unnecessary data / download = 5 TB unnecessary data / day ~ 150TB /month, and this is not only network traffic but also storage space in the user side.
