### ISSUE TITLE
Changelog descriptions not shown on Flathub.org unless they are wrapped in paragraph/p tags

### ISSUE THREAD

**Issue by Dretch** [flathub/flathub#5304]
The documentation at https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Releases.html does not say that `<p>` tags are required, nor does `flatpak-builder-lint`.

However, it seems that, without `<p>` tags, nothing will show on the Flathub website.

Example:
- Currently https://flathub.org/apps/io.github.Dretch.MonomerFlatpakExample is showing a description. This is because the description has `<p>` tags: https://github.com/Dretch/monomer-flatpak-example/blob/db62fd30dc697bbcf7288cde7a21fcd8e5ba6033/assets/io.github.Dretch.MonomerFlatpakExample.metainfo.xml#L31
- Previously, without `<p>` tags, no description was shown (https://github.com/Dretch/monomer-flatpak-example/blob/0ae5d692fd1bfb96c7bdf4a7a81060ebc07fc27e/assets/io.github.Dretch.MonomerFlatpakExample.metainfo.xml#L31).

So it seems to me that either Flathub.org should show descriptions without paragraph tags, or the documentation/linter should reject such descriptions.

**Comment by bbhtt** [comment]
A description tag always requires a child `<p>` `<ol>` or `<ul>` tag, the last two requires at least one child `<li>` tag.

If you have something like:

```xml
  <description>
    Foo
  </description>
```

it will fail validation with `app-description-required`. Same is supposed to happen with descriptions under `release` tags but this is not being checked by appstream. Please report it to https://github.com/ximion/appstream. This does not seem to be mentioned in the official spec, so that is another issue that should be raised there.

It is correct that description is not shown when there is no `p` or `ol` or `ul` tags.

**Comment by bbhtt** [comment]
Both the formats given here https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#release and https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#description show this.

I'm not sure why the spec is missing it, might be that it was overlooked.
