### ISSUE TITLE
Remove "Temple Driver"

### ISSUE THREAD

**Issue by lionirdeadman** [flathub/flathub#5414]
This game: https://flathub.org/apps/com.voxdsp.TempleDriver

The game's description has the following:
"KILL CIA GLOWIES"

This is a reference to this, and it is pretty obvious considering the game is a tribute to Terry A. Davis:
> He was controversial for his regular use of offensive slurs, including racist and homophobic epithets and sometimes rebuked his critics as "CIA [n-word]". In one widely circulated YouTube video, he claimed that "the CIA n-word glow in the dark; you can see them if you're driving. You just run them over."
[Wikipedia](https://en.wikipedia.org/wiki/Terry_A._Davis#Recognition,_controversy_and_following)

Please just remove this. Flathub should not be promoting this.

**Comment by bbhtt** [comment]
Hello @BeverlyCode, please refrain from submitting these type of games on Flathub.

This escaped initial review because I wasn't aware of the context behind the term but this is unsuitable for Flathub.

I have EOL-ed it and archived the repository. If you are willing to change the in-game content and descriptions please comment below.
