### ISSUE TITLE
Add COSMIC runtime

### ISSUE THREAD

**Issue by jackpot51** [flathub/flathub#5654]
According to https://docs.flathub.org/docs/for-app-authors/runtimes/#submission-process, "Runtime developers may submit a ticket to the Flathub issue tracker requesting that their runtime be added to Flathub."

I am working on a runtime for COSMIC applications to simplify some common items, namely installing `just` and the required icon themes. The source code can be found here: https://github.com/pop-os/cosmic-flatpak-runtime/. The guidelines around runtimes are sparse, and I need help to understand them. For example, there is a listed requirement "CI/CD workflow: Flathub uploads must be automated as a part of the regular build/update process for the runtime, so that security updates are not delayed". I would of course want to do this, but I do not have the ability to upload to flathub at this time so I am unable to test such CI.

This would simplify #5649 and #5648, I'm requesting review by @bbhtt who has reviewed these COSMIC apps.

**Comment by bbhtt** [comment]
Having another runtime is probably not worth it due to the maintenance overhead of maintaining multiple branches, guaranteeing security updates/rebuilds and ABI/API compatibility and also to prevent fragmentation for end users.

Unless you have several 100s of modules like KDE has for Qt + KDE components.

Looking at the modules, `just` seems to be a build only dependency and isn't needed by end users (runtimes are installed by end users). The rest are icon and theme which only account for a few MBs.

What you most likely want is a baseapp similar to the Elementary baseapp we have?

**Comment by bbhtt** [comment]
> A baseapp could be good, is there an example of an app derived from the elementary baseapp?

Elementary moved things to their own store a while ago, so we don't get regular submissions for it. But there is a bunch of older ones using it. https://github.com/search?q=org%3Aflathub+%22io.elementary.BaseApp%22&type=code&p=1

**Comment by jackpot51** [comment]
Thanks, I will look into this.

**Comment by jackpot51** [comment]
Would a base app mean that the icons would be included in every app deriving from it, or would they just be downloaded once?

**Comment by jackpot51** [comment]
If I want to make a baseapp, what do I do next?

**Comment by jackpot51** [comment]
So, if two apps use the same baseapp with the icons, will they be stored on disk just once?

**Comment by jackpot51** [comment]
This sounds ideal, then, and simpler than a runtime by far.
