### ISSUE TITLE
Indicate on flathub.org Whether a Flatpak is Built from Source or Binary During Build Process on Flathub

### ISSUE THREAD

**Issue by adrelanos** [flathub/flathub#5733]
### Problem Statement:
Flathub currently lacks transparency in showing whether a Flatpak application is built from source code or if prebuilt binaries are used during the build process. Many users who care about software freedom, security, and reproducibility prefer source-built applications over precompiled binaries. While an application may be open-source, it could still be downloaded as a binary from upstream, bypassing the benefits of building from source. This distinction is especially important for those who value transparency and the integrity of software distribution.

### Importance of Source-built Applications:
Reproducible builds, which are becoming a critical goal in software distribution, hold more value if the software is compiled from source, rather than being downloaded as a precompiled binary. While Flathub may eventually accomplish the goal of reproducible builds, its value would be diminished if many of the Flatpaks available are simply redistributed binaries from upstream. Transparency in this area would empower users to trust the builds more and make informed decisions.

### Comparison with Other Ecosystems:
In the Debian community, the idea of removing embedded copies of code or binaries from upstream source packages is strongly encouraged to improve security and clarity in open-source software development. As the [Debian Wiki on Embedded Copies](https://wiki.debian.org/EmbeddedCopies) explains:
> “Embedded copies (of code, data, fonts or other things) should be removed from the upstream VCS and source tarballs. Upstream might want to only embed the copies in the binary packages they distribute.”

This concept is highly relevant to Flatpak's goals as well, as users expect the same level of scrutiny and transparency.

### Proposed Solution:
1. **Metadata Update**: Introduce a new field in the app metadata indicating whether a Flatpak is built from source or downloaded as a binary during the build process.
2. **UI Integration**: Display this information prominently on the Flathub website for each application, alongside existing metadata such as developer and license details.
3. **CLI Support**: Extend the Flatpak CLI to display this information when querying app details, such as using `flatpak info`.
4. **Automated Detection**: As part of the build process, have the build system automatically detect and log whether the build was from source or binary and update the metadata accordingly.
5. **Subset**: `verified_floss_source`

### Benefits:
- **Increased Transparency**: Users can make more informed choices about the software they install, especially if they prioritize open-source and source-built applications.
- **Support for Reproducible Builds**: Providing transparency into whether a build is from source or binary would add credibility to reproducible builds efforts on Flathub.
- **Trust and Security**: Source-built applications reduce the risk of hidden vulnerabilities or proprietary code being introduced during the build process, improving trust in the ecosystem.

**Comment by bbhtt** [comment]
This is not possible to do in automated or manual fashion unless you go through every single dependency built through the app manifest.

We talked about this internally before and this is not a heuristic/automation we would invest time in.

**Comment by adrelanos** [comment]
How about letting the Flatpak manifest file declare if it was built from source code or is downloading a binary?

**Comment by bbhtt** [comment]
Maintainers can lie, you can't rely on metadata from Metainfo files or manifests. 

If we were to do something like this it has to be auto detected and inserted after the build is done when the build artifacts are outside of the control of the maintainer and ready to be published.

**Comment by hfiguiere** [comment]
> How about letting the Flatpak manifest file declare if it was built from source code or is downloading a binary?

And how would you do that? Please include all the necessary PR to all the components.

**Comment by bbhtt** [comment]
If you audited a subset of packages and confirmed they are fully built from source etc., and you want some metadata to consume for your app store frontend/OS, you can ask app authors to write a `custom` tag in their Metainfo files (see the Appstream specification on custom tags).

We proagate all custom tags to catalogue so that downstreams can use them.

Then you can use that metadata from your end to show only a subset of fully source built/de-vendored apps.

This doesn't solve the "abuse" issue but it should be possible for downstreams to implement a "blocklist" on their end if you see someone mis using it.

But at the moment doing this at scale in an automated fashion is not possible for us.

**Comment by geekley** [comment]
It's really disappointing that this is a non-goal. I hope one day this can be reconsidered. Commenting here to subscribe.

Flathub is becoming the de-facto standard way for many apps to do Linux distribution, but it lacks this important feature present in other stores like Debian/Ubuntu APT and F-Droid. It's difficult for users themselves to go through the manifest every time to try to understand whether it's really built from source or not. Because "open-source" doesn't mean it's necessarily built from source.

**Comment by geekley** [comment]
It would be great if maintainers could at least add a "not-built-from-source" tag. By that I mean:
- Allow a `built-from-source` tag with values `yes`, `no` and the default `unknown`.
- Calculate the result `fully-built-from-source` as `no` if any dependency has `built-from-source=no`, or `unknown` otherwise. Even if you cannot guarantee a `yes`, this is still very valuable info.

If automated checking is ever implemented later:
- Check only `built-from-source=yes` tags, and `fully-built-from-source` can be `yes` if all dependencies are a valid `yes`.

This way simple dependencies used by other code can start adding this tag to claim reproducibility or at least non-reproducibility, and eventually maybe this could be added for fully checking apps.

**Comment by bbhtt** [comment]
Since this issue generated some discussion today in #flathub...

I closed this saying  

> this is not a heuristic/automation we would invest time in.

and that still has not changed today. 

We don't have any immediate need for this and we probably won't have time to work on this in the near future. And please don't expect the 5 or so volunteers who work on Flathub in their free time to do things.

But us not supporting or planning to work on something doesn't mean someone shouldn't try to implement the things they want in other parts of the ecosystem i.e. Flatpak or appstream etc.

Specifically only the UI integration and the subset part relates to Flathub and that comes after the rest of the work is done. 

The rest of the plan discussed in OP has nothing to do with Flathub specifically.

If someone wants to:

- Add a metadata field to Flatpak/AppStream/etc. 
- Create something like diffoscope to analyse sources for binary-ness (this again has nothing to do with flatpak/flatpak-builder, you will be analysing files, it can be an src rpm or src deb or a random git repo)
- ...

, then they should go ahead without us.

Obviously the desicion to use said tooling (if it starts existing) or add a verified_sourcebuild/whatever subset or add UI to flathub.org will be on us and I won't make any promises about that as that is too much in the future.
