### ISSUE TITLE
Why is 'Visual Studio Code' marked as `License: Proprietary`?

### ISSUE THREAD

**Issue by knocte** [flathub/flathub#685]
Case in point: https://flathub.org/apps/details/com.visualstudio.code

As the "publisher" is "flathub maintainers", I'm opening the issue here. Visual Studio Code is MIT licence according to this: https://github.com/Microsoft/vscode

**Comment by nedrichards** [comment]
Because the binaries that this package distributes are prioprietary: https://github.com/flathub/com.visualstudio.code/blob/master/com.visualstudio.code.appdata.xml links to the VS Code licencing page: https://code.visualstudio.com/license which makes it clear.

Flathub also has an open source rebuild of VS Code which is MIT https://flathub.org/apps/details/com.visualstudio.code.oss
