### ISSUE TITLE
Can't see app info on flathub.org

### ISSUE THREAD

**Issue by plfiorini** [flathub/flathub#687]
This happens with Liri Text (https://flathub.org/apps/details/io.liri.Text) as well as Blender (https://flathub.org/apps/details/org.blender.Blender).

Title says "App not found".

The only difference is that after a while the Blender page is loaded.
Sometimes it opens immediately.

**Comment by plfiorini** [comment]
![screenshot from 2018-10-19 21-10-47](https://user-images.githubusercontent.com/843710/47238755-793edd00-d3e3-11e8-8027-5ab05c2b3e2c.png)

**Comment by TingPing** [comment]
I know this isn't helpful (we should give better errors) but its almost certainly just you have something missing in your appdata file.

**Comment by TingPing** [comment]
Glancing at your info I don't see an obvious problem. Maybe @jgarciao can see what is missing on the webapp side.

**Comment by plfiorini** [comment]
If it helps at some point `<summary>` was missing from io.liri.Text, but yesterday I made a new release adding that tag and cleaned up other stuff but still I can't see the page.
And Blender sometimes works sometimes doesn't.

**Comment by TingPing** [comment]
Blender shows up fine here so I don't think its related even if its slow.

**Comment by encombhat** [comment]
Happens on me. org.eu.encom.spectral, com.github.rssguard, io.github.mujx.Nheko, etc.

**Comment by TingPing** [comment]
@encombhat Then report this against those applications. Their appdata just has problems to solve.

**Comment by har9862** [comment]
You do want to add the missing OARS information to your appdata file as that's a [Flathub requirement](https://github.com/flathub/flathub/wiki/App-Requirements#appstream). That can be easely generated by using the [OARS-generator](https://hughsie.github.io/oars/generate.html). Answer a few questions and paste the result to your appdata file somewhere inside the `<component></component>` tags.

I did a tiny [PR](https://github.com/lirios/text/pull/47), but did not include the OARS information as you are better to answer these questions correctly.

I'm not sure, but I don't think that the ".desktop" part in the ID should be there. Maybe that could be why Flathub claims it cannot find your app?
I see that Atom currently has the very same issue of not being found on Flathub and Atom also has a ".desktop" part in [its appdata](https://github.com/flathub/io.atom.Atom/blob/master/io.atom.Atom.appdata.xml). @Pointedstick any thoughts on this?

**Comment by Pointedstick** [comment]
The trailing `.desktop` bit should indeed not be used. It's deprecated legacy according to @ximion, the AppStream creator.

**Comment by ximion** [comment]
On new components, yes - we have the more flexible [launchable tag](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-launchable) for defining how an app can be launched via .desktop files now.
The component-ID should ideally be static and never-changing, as it is used to identify the app across systems and associate additional data (like reviews) with it.

**Comment by jgarciao** [comment]
io.liri.Text information not being shown in flathub.org will be fixed in production this week. It's already tracked in this issue https://github.com/flathub/io.liri.Text/issues/1

For the rest of apps, it was probably a temporally problem with the website because now they work fine:
- https://flathub.org/apps/details/org.blender.Blender
- https://flathub.org/apps/details/org.eu.encom.spectral
- https://flathub.org/apps/details/com.github.rssguard
- https://flathub.org/apps/details/com.github.quaternion
- https://flathub.org/apps/details/com.scoutshonour.dtipbijays
- https://flathub.org/apps/details/org.armagetronad.ArmagetronAdvanced

io.github.mujx.Nheko is marked as end of life:
```
flatpak remote-ls -d flathub | grep io.github.mujx.Nheko
app/io.github.mujx.Nheko/x86_64/stable	f517b55993ad	8,4 MB	3,0 MB	eol=This application is no longer maintained.
```

**Comment by plfiorini** [comment]
@har9862: Merged your PR and added OARS information. Thanks.

**Comment by fedelibre** [comment]
> You do want to add the missing OARS information to your appdata file as that's a [Flathub requirement](https://github.com/flathub/flathub/wiki/App-Requirements#appstream).

AFAICS it doesn't state that OARS is mandatory.

I thought that passing the appstream-util validation would be enough.
If an application passes the validations, gets merged and then it's not displayed on flathub website because there's something wrong in the appdata file, then this is a bug.

I'm in the process of trying to understand why [org.gnome.NautilusPreviewer](https://github.com/flathub/org.gnome.NautilusPreviewer) doesn't show up on flathub.org. I'm patching the appdata file until I find the problem.

**Comment by barthalion** [comment]
NautilusPreviewer is not displayed because it's not an actual application: `<component type="addon">`

**Comment by fedelibre** [comment]
Mmmmh, why not displaying addons? I would expect flathub.org to return the same results of a search in a software center application.

**Comment by barthalion** [comment]
I don't see NautilusPreviewer being listed in my GNOME Software as a separate application either, so it's not really different. We currently don't display addons because it's not useful as standalone entries, and showing available addons for specific apps is planned.

**Comment by fedelibre** [comment]
This is what I see in GNOME Software:
![Schermata da 2022-02-16 13-29-33](https://user-images.githubusercontent.com/1644647/154265377-69af2d78-48c5-4d48-a1bb-48ebba450346.png)

I guess that the "wheel icon" identifies Sushi as an extension?
But at least it is listed in the search results.

Happy to know that showing available addons for specific apps is planned.
Thanks
