### ISSUE TITLE
Split FOSS and Proprietary repositories

### ISSUE THREAD

**Issue by gjsman** [flathub/flathub#691]
Several distributions including Fedora and Purism have had worries about including Flathub by default because it contains Proprietary software by default (for example, https://bugzilla.redhat.com/show_bug.cgi?id=1462548, https://discussion.fedoraproject.org/t/flathub-and-proprietary-software/273). 

For this reason, please consider splitting the Proprietary and FOSS sides of Flathub into separate repositories, so that distributions can ship only with the FOSS repository by default.

**Comment by TingPing** [comment]
This has been discussed before but I'm not sure there was any conclusion: CC @ramcq @alexlarsson

**Comment by ramcq** [comment]
It's in our mind behind the work @alexlarsson is doing for https://lists.freedesktop.org/archives/flatpak/2018-September/001259.html - but to meet the Purism requirements, to be "FSF approved", having a separate free and non-free repository is not acceptable due to referring to non-free software (Debian is not, for example). The idea was that we could potentially apply a server-side filter and produce a subset of the repository summary/metadata files which contained only free-as-in-freedom licensed things, and create a clone "librehub" (except not this name) website/domain which was the same as Flathub but with the proprietary software removed, and share the CDN/cache/objects etc infrastructure.

**Comment by gjsman** [comment]
@ramcq Perhaps this could be simple as a custom list. "librehub" just takes "flathub" and returns everything except the packages on the "nonfree" list. This would be pretty quick to implement, just a `return all WHERE name != Names On The List." Ideally something more long-term would be created, but it wouldn't be a bad short term solution.

**Comment by gjsman** [comment]
As for references to non-free software, perhaps we could have software "aliases." For example, If my package refers to something proprietary (e.g. NVIDIA drivers), give the user a prompt asking if you want to install the non free software, do nothing (don't install the drivers), or install something else (e.g. open source drivers). Complicated... just thinking out loud.

**Comment by 4jNsY6fCVqZv** [comment]
Hello, the problem still exists and contains some ethical implications for me, which unfortunately lead to the fact that I must exclude the use of Flathub. What are your current thoughts about solving this problem for Free Software only users? @ramcq @alexlarsson

**Comment by Vanadiae** [comment]
Hello,

This is somewhat of a problem because even GNOME developers requires to activate proprietary software from flathub to access the versioned GNOME runtimes. And as flathub contains proprietary software, I won't activate the repository even if there is some cool free software out there that I'd like to try and to experiment deeper Flatpak. So if I can help in some ways to achieve that, separating to a "libre" flathub and "proprietary" flathub would be awesome !

**Comment by gjsman** [comment]
@ramcq I've been revisiting this as I've been playing with Fedora Silverblue, where the lack of Flathub as a default is a serious problem (as Silverblue only supports Flatpaks for apps, and Fedora's Flatpak repository is much smaller). IMHO, I don't think that FSF approval is as much of a priority as getting Flathub into Silverblue would be. Even if splitting the repos doesn't get FSF approval, at least it might get Fedora approval, which could be extremely useful in the near future. Fedora has plans to make Silverblue the preferred OS type (instead of the current Workstation) and has been working towards that. Getting this sorted out before that happens needs to be a high priority.

**Comment by 4jNsY6fCVqZv** [comment]
Are there people here who would like to contribute to a FOSS compatible solution?

**Comment by 4jNsY6fCVqZv** [comment]
Are there people out there who would like to contribute to a FOSS compatible solution?

**Comment by A6GibKm** [comment]
@gjsman flathub cant be the default for Fedora as it conflicts with their policy. Fedora can only ship stuff built with their own infrastructure, and flathub is not theirs.

**Comment by razzeee** [comment]
The usecase has been solved by adding/using subsets now, so I think this should be closed

**Comment by bbhtt** [comment]
Documented here https://docs.flathub.org/docs/for-users/installation#subsets, closing.
