### ISSUE TITLE
Java runtime

### ISSUE THREAD

**Issue by Mailaender** [flathub/flathub#71]
Seeing https://github.com/flathub/flathub/pull/34 I wonder if it would make more sense if there would be a Java runtime instead of every application shipping their own JRE. Found nothing at http://flatpak.org/runtimes.html yet, so I would like to discuss best practice like how to build them and where to place it.

**Comment by Barthalion** [comment]
I wonder if extension maintained here on Flathub wouldn't be better. @TingPing ?

**Comment by AsavarTzeth** [comment]
Not to mention building something like the openjdk jre is not very straight forward. Just as a starter, icedtea requires the apache ant build system. However to first build the apache ant you require a java runtime...

**Comment by adityashah1212** [comment]
I am working on this but I have a problem on which I have been stuck for a while, apparently make install in jdk uses cp to install and not install, but it fails to copy using cp, have a look at https://github.com/flatpak/freedesktop-sdk-images/issues/30

**Comment by alexlarsson** [comment]
I made an openjdk SDK at some point:
https://gist.github.com/anonymous/c5a4780604949256c4ee146403f8826d

Its not very tested though, and it needs ostree 2017.11 to build (due to the issue @adityashah1212 points out). Would be cool if people did some testing on this. Even cooler if someone could extend it to work with arm and aarch64.

**Comment by nedrichards** [comment]
Resolved by https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk9 which is cool! Although it could still get better with ARM usage and could do with a bit of documentation.
