### ISSUE TITLE
Update to flatpak 1.2.1 and flatpak-builder 1.0.4

### ISSUE THREAD

**Issue by MatMaul** [flathub/flathub#841]
I don't know exactly where flatpak and flatpak-builder are from in the build slaves, but flatpak 1.2.1 and flatpak-builder 1.0.4 just got released with some patches of mine needed to build VLC Blu-ray plugin.

If you can kindly let me know when you update them it would be nice. Or do you use an auto-updated Fedora in this case I just have to wait a bit ?

Thanks

**Comment by nedrichards** [comment]
It's mostly CentOS running flatpak versions from https://copr.fedorainfracloud.org/coprs/amigadave/flatpak-epel7/ I know that in this case we're updating ASAP to the latest because we need these releases to build LibreOffice and a few other things. @ramcq is a better person to ask for the latest info though.

**Comment by ramcq** [comment]
I did that earlier today.

**Comment by MatMaul** [comment]
@ramcq great thanks for the rapidity ! After checking however it seems like flatpak-builder 1.0.4 build is in failure in the copr.

**Comment by ramcq** [comment]
Yeah, the builders are all on Ubuntu, so this doesn't matter.
