### ISSUE TITLE
Consider using Mirrorbits to set up community-based mirroring?

### ISSUE THREAD

**Issue by cheese** [flathub/flathub#965]
Mirrorbits[1] is a tool to manage mirroring system with a single hostname. Community mirroring sites can join.
[1] https://github.com/etix/mirrorbits

**Comment by TingPing** [comment]
Considering that readme says Endless OS uses it I'm sure @ramcq is familiar with it and had reasons to not choose it.

**Comment by ramcq** [comment]
ostree repos are just not amenable to directly mirroring in this way - Flathub is now around a terabyte with hundreds of thousands of files. You need a caching proxy (ie a CDN) to effectively move ostree repos closer to the edge because they are content addressed - you can't use the file structure to predict reachability / relevance. In any case, we have fully sponsored CDN bandwidth from Fastly - giving very little incentive to start building our own CDN, even supposing community endpoints would want to run eg a container defined by us.

**Comment by cheese** [comment]
That's related to #813 . So investing to Fastly seems the unique method to improve Flathub accessibility for a specific area.

**Comment by ramcq** [comment]
I hadn't seen that issue, I was just explaining why we've not bothered to look for traditional mirrors. Even flowing redirects during the ostree fetch process massively harms throughput.
